= På drift efter Virtú

"När konstnären "[...] väl upptäckt och uttryckt sin virtú, kan konstnären börja resa sitt mikrokosmos. [...] När konstnären upptäckt sin egen styrka, är det troligare att han urskiljer och tar hänsyn till en speciell virtú hos andra [...] Resandet av ett mikrokosmos består i att kunna skilja på dessa övriga krafter och i att hålla dem i prydlig ordning omkring sin egen." 
Källa: Ezra Pound, Vortex

Jag har en ömsom erbarmlig, ömsom episk _känsla_ av allting redan är skrivet. Jag får den av att läsa saker som skrevs i svunna årtusenden. Som skriftställare, är jag benägen att agera på känslan: 

* Lägga tid på att upprepa, efterapa och misstolka mig själv som nyskapande?
* Eller motbevisa att allt skulle vara skrivet?

Gudskelov, så har majoriteten av min produktion – i all sin ungdomliga frenesi, bristfällighet och naivitet – gått åt till psykologisk automatism, samt förädling (editering, redigering) med hänsyn till ett visst intuitivt önskat sätt att uppleva poesi. 

Detta utesluter dock inte att jag har rätt i övertygelsen: Allt är redan skrivet. Och om jag då ändå skriver, är det inte enligt min egen övertygelse. Detta härleder mig att tro att mitt skrivande bara är en symbolhandling – ett surrigat för något annat, ett svar på en fråga jag upplever är ställd till just mig. 

För att återknyta till rubriken, eller grunda den i vad som komma skall, vill jag förtydliga på vilket sätt jag är på drift: 

Inte på jakt!, ty min intention är att undanröja symbolhandlingens allmänmänskliga innehållsfattighet. 
Att göra någonting för att _jag tror att det är någonting jag måste_. Jag känner inte att jag behöver jaga, jakten är en för laddad metafor för mig som modern varelse att behöva slava under. Jag föredrar det likgiltiga, passiva, ostressade. 

På drift, i stället, av dikotomisk nödvändighet – sökande efter, utan egentlig agens. På drift emot någonting specifikt. Man skulle nästan kunna säga, att jag ämnar söka reda på någonting. 

Om vi ska tala om sökande, är det i strikt mening för mig, enbart efter _axiom_, _ankarpunkter_, eller _ofrånkomliga sanningar_ – ofrånkomliga i det att de har inträffat och därigenom tagit plats i mig. Denna agens måste tillskrivas mig. En retrospektiv inåtgång efter personliga egenskaper, som på olika sätt påverkat textproduktionen under skrivande år. 

=== Att sikta högt och landa djupt

Jag ämnar drifta emot min konstnärliga övertygelse, möta den. Inget mer, inget mindre. Vadän som i övrigt sker, är oberoende av denna texts syfte. 

Rädslan för, eller insikten om, risken för symbolhandlingar underblåser alltså ovan beskrivna intention. Jag ser möjligheten som en risk, därför att jag ser tiden som någonting att spendera och att spendera tid _åt_ symbolhandlingar vore som att kanalisera resurser _på_ ett sätt som inte tjänar mig själv. Att inte vara varse vem det tjänar och trots detta fortsätta riskerar att vara på sin höjd religiöst, i sämsta fall barnsligt. 

Nu, en tanke om att detta är ett fynd i sig: att denna text blir till, motsvarar vad jag letar efter. Tillåt mig att vara barnsligt religiös till skrivandets förmåga att tänka åt mig. 

== Spekulationer om bärkraftiga beteenden

När jag försöker föreställa mig unikt återkommande tendenser i mitt fria skapande, erinras mig först och främst två övertygelser. Två övertygelser som inte är direkt influerade, ergo, inte medvetet anammade efter inträffad influens (sådana finns också). 

. Memen i mig, den _intuitiva självklarheten_ i att allt går igen: Att vara, att vara det, att vara den. Syntetiserat genom själavandring och sedermera simulationsteori: en _överväldigande hopplös_ repetition/kopia/nyversion. 
. Bristvaran och modet; kompensationen som skäms för sig. Illviljan att acceptera omvärldens delaktighet – viljan att inkludera närän omvärlden medverkar. Smärtande insikt genom oupptäckt utanförskap, å ena sidan – å andra sidan tafatt inifrånverkande genom upplevd funktion.   

=== Den intuitiva självklarheten
Du ser dig själv ta slut, men upplever dig oändlig. Så förstår du världen utanför din kropp, också. En intuition, en av rådande omständigheter syntetiserad projektion kring sakernas tillstånd. Huruvida intuitionen håller eller ej består av utomstående faktorer – när intuitionen slagit till är den självklar. 

Med det intuitiva _ögat_ som enda måttstock, blir jag öppnad för världen i större omfattning än via, exempelvis, den rationella måttstocken. 

=== Å ena sidan – å andra sidan 
Spännvidden mellan två kraftfulla reaktioner:

* Avståndstagande, självamplifierande mani
** Vid upptäckt vänds rörelsen emot den andra polen
* Oförsonlig, normbrytande överspillan 
** Vid upptäckt vänds rörelsen emot den andra polen

==== "Bristvaran och modet"
Som barn, ofullständig – med mod att stå för vadän det ofullständiga innebär. Senare, oförmögen att uppskatta sentenser som "barnets fullkomlighet". Uppenbarligen utsatt, sårbar. Att undgå medvetandegöra rädslan och agera utifrån den – ett lurat utfall. "Det finns en vildmark, vi lver mitt i den, oavsett vad folk säger", skulle kunna vara ett citat från min mun. 